const words = [
 { original_word: "Abundant", hindi_translation: "प्रचुर", antonyms: "scarce, rare, limited", hindi_antonyms: "कमी, दुर्लभ, सीमित" },
  { original_word: "Abolish", hindi_translation: "उन्मूलन करना", antonyms: "Enact", hindi_antonyms: "कानून बनाना" },
  { original_word: "Abash", hindi_translation: "लज्जित करना", antonyms: "Uphold, Discompose", hindi_antonyms: "सहन करना, असंगत करना" },
  { original_word: "Absolve", hindi_translation: "मुक्त करना", antonyms: "Compel, Accuse", hindi_antonyms: "बलात्कृत करना, आरोप लगाना" },
  { original_word: "Acumen", hindi_translation: "प्रज्ञा", antonyms: "Stupidity, Ignorance", hindi_antonyms: "मूर्खता, अज्ञानता" },
  { original_word: "Accord", hindi_translation: "सहमति", antonyms: "Discord", hindi_antonyms: "विरोध" },
  { original_word: "Adamant", hindi_translation: "अडिग", antonyms: "Flexible, Soft", hindi_antonyms: "लचीला, मुलायम" },
  { original_word: "Adversity", hindi_translation: "कठिनाई", antonyms: "Prosperity, Fortune", hindi_antonyms: "समृद्धि, भाग्य" },
  { original_word: "Alleviate", hindi_translation: "कम करना", antonyms: "Aggravate, Enhance", hindi_antonyms: "बढ़ाना, सुधारना" },
  { original_word: "Amplify", hindi_translation: "वृद्धि करना", antonyms: "Lessen, Contract", hindi_antonyms: "घटाना, संकुचित करना" },
  { original_word: "Ascend", hindi_translation: "चढ़ना", antonyms: "Descend, Decline", hindi_antonyms: "उतरना, गिरना" },
  { original_word: "Audacity", hindi_translation: "हिम्मत", antonyms: "Mildness, Cowardice", hindi_antonyms: "नम्रता, कायरता" },
  { original_word: "Awkward", hindi_translation: "अजीब", antonyms: "Adroit, clever", hindi_antonyms: "कुशल, चतुर" },
  { original_word: "Axiom", hindi_translation: "सूत्र", antonyms: "Absurdity, Blunder", hindi_antonyms: "बेवकूफी, गड़बड़ी" },
  { original_word: "Baffle", hindi_translation: "हैरान करना", antonyms: "Facilitate, Clarify", hindi_antonyms: "सहायक बनाना, स्पष्ट करना" },
  { original_word: "Bewitching", hindi_translation: "मोहक", antonyms: "Repulsive, Repugnant", hindi_antonyms: "घृणास्पद, अप्रिय" },
  { original_word: "Bustle", hindi_translation: "हलचल", antonyms: "Slowness, Quiet", hindi_antonyms: "धीमेपन, शांत" },
  { original_word: "Busy", hindi_translation: "व्यस्त", antonyms: "Idle, Lazy", hindi_antonyms: "आलसी, सुस्त" },
  { original_word: "Calamity", hindi_translation: "आपदा", antonyms: "Fortune", hindi_antonyms: "भाग्य" },
  { original_word: "Callous", hindi_translation: "निर्दय", antonyms: "Compassionate, Tender", hindi_antonyms: "दयालु, कोमल" },
  { original_word: "Cease", hindi_translation: "रोकना", antonyms: "Begin, Originate", hindi_antonyms: "शुरू करना, उत्पन्न करना" },
  { original_word: "Chaste", hindi_translation: "पवित्र", antonyms: "Sullied, Lustful", hindi_antonyms: "दागी, वासनापूर्ण" },
  { original_word: "Comprise", hindi_translation: "शामिल होना", antonyms: "Reject, lack", hindi_antonyms: "नकारना, कमी होना" },
  { original_word: "Classic", hindi_translation: "प्रामाणिक", antonyms: "Romantic, Unusual", hindi_antonyms: "रोमांटिक, असामान्य" },
  { original_word: "Concur", hindi_translation: "सहमत होना", antonyms: "Differ, disagree", hindi_antonyms: "विभिन्न होना, असहमत होना" },
  { original_word: "Consolidate", hindi_translation: "संगठित करना", antonyms: "Separate, Weaken", hindi_antonyms: "अलग करना, कमजोर करना" },
  { original_word: "Compress", hindi_translation: "संपीड़ित करना", antonyms: "Amplify, Expand", hindi_antonyms: "वृद्धि करना, फैलाना" },
  { original_word: "Decipher", hindi_translation: "सुलझाना", antonyms: "Misinterpret, distort", hindi_antonyms: "गलत अर्थ लगाना, विकृत करना" },
  { original_word: "Demolish", hindi_translation: "नष्ट करना", antonyms: "Repair, construct", hindi_antonyms: "मरम्मत करना, निर्माण करना" },
  { original_word: "Dwarf", hindi_translation: "बौना", antonyms: "Huge, Giant", hindi_antonyms: "विशाल, दैत्य" },
  { original_word: "Eager", hindi_translation: "आतुर", antonyms: "Indifferent, apathetic", hindi_antonyms: "उदासीन, निष्क्रिय" },
  { original_word: "Endeavour", hindi_translation: "प्रयास", antonyms: "Cease, quit", hindi_antonyms: "रोकना, छोड़ना" },
  { original_word: "Enormous", hindi_translation: "विशाल", antonyms: "Diminutive, negligible", hindi_antonyms: "छोटा, तुच्छ" },
  { original_word: "Epitome", hindi_translation: "सार", antonyms: "Increment, expansion", hindi_antonyms: "वृद्धि, विस्तार" },
  { original_word: "Fabricate", hindi_translation: "निर्माण करना", antonyms: "Destroy, Dismantle", hindi_antonyms: "नष्ट करना, ध्वस्त करना" },
  { original_word: "Feeble", hindi_translation: "कमजोर", antonyms: "Strong, Robust", hindi_antonyms: "मजबूत, स्वस्थ" },
  { original_word: "Ferocious", hindi_translation: "भयंकर", antonyms: "Gentle, Sympathetic", hindi_antonyms: "मुलायम, सहानुभूति" },
  { original_word: "Feud", hindi_translation: "विरोध", antonyms: "Harmony, fraternity", hindi_antonyms: "संगति, भाईचारा" },
  { original_word: "Fluctuate", hindi_translation: "लहराना", antonyms: "Stabilize, resolve", hindi_antonyms: "स्थिर करना, समाधान करना" },
  { original_word: "Gather", hindi_translation: "संग्रह करना", antonyms: "Disperse, Dissemble", hindi_antonyms: "विखंडित करना, छिपाना" },
  { original_word: "Gorgeous", hindi_translation: "सुंदर", antonyms: "Dull, unpretentious", hindi_antonyms: "निरस, सामान्य" },
  { original_word: "Gracious", hindi_translation: "दयालु", antonyms: "Rude, Unforgiving", hindi_antonyms: "असभ्य, कठोर" },
  { original_word: "Genuine", hindi_translation: "असली", antonyms: "Spurious", hindi_antonyms: "झूठा" },
  { original_word: "Gloomy", hindi_translation: "उदास", antonyms: "Gay, Bright", hindi_antonyms: "खुश, उज्जवल" },
  { original_word: "Hamper", hindi_translation: "विघ्न डालना", antonyms: "Promote, facilitate", hindi_antonyms: "बढ़ावा देना, सहायक बनाना" },
  { original_word: "Hazard", hindi_translation: "खतरा", antonyms: "Conviction, security", hindi_antonyms: "आस्था, सुरक्षा" },
  { original_word: "Humble", hindi_translation: "नम्र", antonyms: "Proud, Assertive", hindi_antonyms: "अहंकारी, आत्मविश्वासी" },
  { original_word: "Humility", hindi_translation: "नम्रता", antonyms: "Boldness, Pride", hindi_antonyms: "साहस, घमंड" },
  { original_word: "Impulsive", hindi_translation: "संवेदनशील", antonyms: "Cautious, Deliberate", hindi_antonyms: "सावधान, जानबूझकर" },
  { original_word: "Indifferent", hindi_translation: "निष्क्रिय", antonyms: "Passionate, Enthusiastic", hindi_antonyms: "जोश, उत्साही" },
  { original_word: "Infer", hindi_translation: "निष्कर्ष निकालना", antonyms: "Misinterpret, misunderstand", hindi_antonyms: "गलत समझना, गड़बड़ करना" },
  { original_word: "Invincible", hindi_translation: "अजेय", antonyms: "Defeated, Vulnerable", hindi_antonyms: "पराजित, संवेदनशील" },
  { original_word: "Jeopardy", hindi_translation: "खतरा", antonyms: "Safety", hindi_antonyms: "सुरक्षा" },
  { original_word: "Jovial", hindi_translation: "हर्षित", antonyms: "Melancholy, Mournful", hindi_antonyms: "उदास, शोकाकुल" },
  { original_word: "Jovial", hindi_translation: "हर्षित", antonyms: "Melancholy, Mournful", hindi_antonyms: "उदास, शोकाकुल" },
  { original_word: "Keen", hindi_translation: "तीव्र", antonyms: "Vapid, Insipid", hindi_antonyms: "नीरस, उबाऊ" },
  { original_word: "Lavish", hindi_translation: "धन्यवादी", antonyms: "Scarce, Deficient", hindi_antonyms: "कमी, अभाव" },
  { original_word: "Lenient", hindi_translation: "सहिष्णु", antonyms: "Cruel, Severe", hindi_antonyms: "क्रूर, कठोर" },
  { original_word: "Liable", hindi_translation: "जवाबदेह", antonyms: "Unaccountable, Apt to", hindi_antonyms: "असंगत, प्रवृत्त" },
  { original_word: "Liberal", hindi_translation: "उदार", antonyms: "Stingy, Malicious", hindi_antonyms: "कंजूस, दुष्ट" },
  { original_word: "Linger", hindi_translation: "टिके रहना", antonyms: "Hasten, Quicken", hindi_antonyms: "जल्दी करना, तीव्र करना" },
  { original_word: "Luscious", hindi_translation: "स्वादिष्ट", antonyms: "Unsavory", hindi_antonyms: "अस्वादिष्ट" },
  { original_word: "Mandatory", hindi_translation: "आवश्यक", antonyms: "Optional", hindi_antonyms: "वैकल्पिक" },
  { original_word: "Masculine", hindi_translation: "पुरुषोचित", antonyms: "Feminine, Meek", hindi_antonyms: "स्त्रीलिंग, मृदु" },
  { original_word: "Modest", hindi_translation: "विनम्र", antonyms: "Arrogant, Pompous", hindi_antonyms: "अहंकारी, घमंडी" },
  { original_word: "Mutual", hindi_translation: "पारस्परिक", antonyms: "Separate, Distinct", hindi_antonyms: "अलग, विशिष्ट" },
  { original_word: "Nimble", hindi_translation: "चुस्त", antonyms: "Sluggish, Languid", hindi_antonyms: "धीमा, सुस्त" },
  { original_word: "Nonchalant", hindi_translation: "उदासीन", antonyms: "Attentive, Considerate", hindi_antonyms: "सावधान, विचारशील" },
  { original_word: "Nullify", hindi_translation: "रद्द करना", antonyms: "Confirm, Uphold", hindi_antonyms: "पुष्टि करना, बनाए रखना" },
  { original_word: "Numerous", hindi_translation: "अनेक", antonyms: "Scarce, Deficient", hindi_antonyms: "कमी, अभाव" },
  { original_word: "Obstruct", hindi_translation: "अवरोध करना", antonyms: "Hasten, Encourage", hindi_antonyms: "जल्दी करना, उत्साहित करना" },
  { original_word: "Obtain", hindi_translation: "प्राप्त करना", antonyms: "Forfeit", hindi_antonyms: "हारी हुई चीज़ खोना" },
  { original_word: "Obvious", hindi_translation: "स्पष्ट", antonyms: "Obscure, Ambiguous", hindi_antonyms: "अस्पष्ट, संदिग्ध" },
  { original_word: "Optimist", hindi_translation: "आशावादी", antonyms: "Pessimist", hindi_antonyms: "निराशावादी" },
  { original_word: "Pacify", hindi_translation: "शांत करना", antonyms: "Irritate, Worsen", hindi_antonyms: "खराब करना, चिढ़ाना" },
  { original_word: "Persuade", hindi_translation: "मनाना", antonyms: "Dissuade, Halt", hindi_antonyms: "विरुद्ध करना, रुकना" },
  { original_word: "Propagate", hindi_translation: "प्रचार करना", antonyms: "Suppress, Deplete", hindi_antonyms: "दबाना, खत्म करना" },
  { original_word: "Progress", hindi_translation: "प्रगति", antonyms: "Retrogress, Worsening", hindi_antonyms: "पिछे जाना, और खराब होना" },
  { original_word: "Prompt", hindi_translation: "तत्काल", antonyms: "Slow, Negligent", hindi_antonyms: "धीमा, लापरवाह" },
  { original_word: "Prudence", hindi_translation: "सावधानी", antonyms: "Indiscretion", hindi_antonyms: "लापरवाही" },
  { original_word: "Pompous", hindi_translation: "घमंडी", antonyms: "Unpretentious, Humble", hindi_antonyms: "साधारण, विनम्र" },
  { original_word: "Quaint", hindi_translation: "अजीब", antonyms: "Familiar, Usual", hindi_antonyms: "परिचित, सामान्य" },
  { original_word: "Quarantine", hindi_translation: "संक्रमण से बचाव", antonyms: "Befriend, Socialize", hindi_antonyms: "मित्रता करना, सामजिक करना" },
  { original_word: "Rebellious", hindi_translation: "विद्रोही", antonyms: "Submissive, Compliant", hindi_antonyms: "विनम्र, आज्ञाकारी" },
  { original_word: "Rectify", hindi_translation: "सुधारना", antonyms: "Falsify, Worsen", hindi_antonyms: "झूठ बोलना, खराब करना" },
  { original_word: "Reluctant", hindi_translation: "अनिच्छुक", antonyms: "Eager, Anxious", hindi_antonyms: "आतुर, घबराया हुआ" },
  { original_word: "Restrain", hindi_translation: "रोकना", antonyms: "Incite", hindi_antonyms: "उत्तेजना करना" },
  { original_word: "Redeem", hindi_translation: "उद्धार करना", antonyms: "Conserve, Lose", hindi_antonyms: "सहेजना, खोना" },
  { original_word: "Remorse", hindi_translation: "पछतावा", antonyms: "Ruthlessness, Obduracy", hindi_antonyms: "निर्दयता, कठोरता" },
  { original_word: "Retract", hindi_translation: "वापस लेना", antonyms: "Confirm, Assert", hindi_antonyms: "पुष्टि करना, दावा करना" },
  { original_word: "Rustic", hindi_translation: "ग्रामीण", antonyms: "Cultured, Refined", hindi_antonyms: "संस्कृत, परिष्कृत" },
  { original_word: "Ruthless", hindi_translation: "निर्दय", antonyms: "Compassionate, Lenient", hindi_antonyms: "दयालु, सहिष्णु" },
  { original_word: "Sacred", hindi_translation: "पवित्र", antonyms: "Ungodly, Profane", hindi_antonyms: "नास्तिक, अपवित्र" },
  { original_word: "Savage", hindi_translation: "जंगली", antonyms: "Polished, Civilized", hindi_antonyms: "संस्कारित, सभ्य" },
  { original_word: "Sarcastic", hindi_translation: "विडंबनात्मक", antonyms: "Courteous, Gracious", hindi_antonyms: "विनम्र, कृपालु" },
  { original_word: "Sympathy", hindi_translation: "सहानुभूति", antonyms: "Antipathy, Discord", hindi_antonyms: "विरोध, मतभेद" },
  { original_word: "System", hindi_translation: "व्यवस्था", antonyms: "Chaos, Disorder", hindi_antonyms: "अराजकता, गड़बड़ी" },  
  { original_word: "Taboo", hindi_translation: "निषिद्ध", antonyms: "Permit, Consent", hindi_antonyms: "अनुमति, सहमति" },
  { original_word: "Taciturn", hindi_translation: "मौन", antonyms: "Talkative, Extrovert", hindi_antonyms: "बोलचाल, बाहरी" },
  { original_word: "Tedious", hindi_translation: "उबाऊ", antonyms: "Exhilarating, Lively", hindi_antonyms: "उत्साही, जीवंत" },
  { original_word: "Temperate", hindi_translation: "मितभाषी", antonyms: "Boisterous, Violent", hindi_antonyms: "कोलाहल, हिंसक" },
  { original_word: "Utterly", hindi_translation: "पूरी तरह से", antonyms: "Deficiently, Incomplete", hindi_antonyms: "अपूर्ण, कमी" },
  { original_word: "Uncouth", hindi_translation: "असभ्य", antonyms: "Elegant, Compensate", hindi_antonyms: "सुशिक्षित, सुधारना" },
  { original_word: "Urchin", hindi_translation: "बच्चा", antonyms: "Creep, Knave", hindi_antonyms: "कृपण, शरारती" },
  { original_word: "Urge", hindi_translation: "प्रेरित करना", antonyms: "Abhorrence, Abomination", hindi_antonyms: "घृणा, घिनौना" },
  { original_word: "Vanity", hindi_translation: "अहंकार", antonyms: "Modesty, Humility", hindi_antonyms: "विनम्रता, नम्रता" },
  { original_word: "Venom", hindi_translation: "विष", antonyms: "Antidote, Benevolent", hindi_antonyms: "प्रतिरोधक, कृपालु" },
  { original_word: "Veteran", hindi_translation: "पूर्व सैनिक", antonyms: "Novice, Tyro", hindi_antonyms: "नवोदित, अनाड़ी" },
  { original_word: "Vicious", hindi_translation: "क्रूर", antonyms: "Noble, Virtuous", hindi_antonyms: "उत्कृष्ट, सद्गुणी" },
  { original_word: "Vigilant", hindi_translation: "सतर्क", antonyms: "Careless, Negligent", hindi_antonyms: "लापरवाह, उदासीन" },
  { original_word: "Wicked", hindi_translation: "दुष्ट", antonyms: "Virtuous, Noble", hindi_antonyms: "सद्गुणी, महान" },
  { original_word: "Wield", hindi_translation: "वापस लेना", antonyms: "Forgo, Avoid", hindi_antonyms: "त्याग करना, बचना" },
  { original_word: "Winsome", hindi_translation: "आकर्षक", antonyms: "Alluring, Rapturous", hindi_antonyms: "मनमोहक, खुशहाल" },
  { original_word: "Yell", hindi_translation: "चिल्लाना", antonyms: "Whisper, Muted", hindi_antonyms: "फुसफुसाना, दबाना" },
  { original_word: "Yield", hindi_translation: "उत्पन्न करना", antonyms: "Resist, Protest", hindi_antonyms: "विरोध करना, विरोध करना" },
  { original_word: "Yearn", hindi_translation: "लालायित होना", antonyms: "Content, Satisfy", hindi_antonyms: "संतुष्ट, संतुलित" },
  { original_word: "Zeal", hindi_translation: "उत्साह", antonyms: "Apathy, Lethargy", hindi_antonyms: "निराशा, आलस्य" },
  { original_word: "Zenith", hindi_translation: "सर्वोच्च बिंदु", antonyms: "Nadir, Base", hindi_antonyms: "न्यूनतम, आधार" },
  { original_word: "Zest", hindi_translation: "उत्साह", antonyms: "Disgust, Passive", hindi_antonyms: "घृणा, निष्क्रिय" },
  { original_word: "Zig-zag", hindi_translation: "झूलना", antonyms: "Straight, Unbent", hindi_antonyms: "सीधा, अडिग" }
];
