const chapters: [
          { lesson_id: 1, characters: "र त", matras: "े ि" },
          { lesson_id: 2, characters: "क च", matras: "ो ्" },
          { lesson_id: 3, characters: "प", matras: "ु" },
          { lesson_id: 4, characters: "ग ज", matras: "ौ ा" },
          { lesson_id: 5, characters: "ह द", matras: "ै ी" },
          { lesson_id: 6, characters: "ब", matras: "ू" },
          { lesson_id: 7, characters: "ट", matras: "ं" },
          { lesson_id: 8, characters: "म ड", matras: "" },
          { lesson_id: 9, characters: "न", matras: "़" },
          { lesson_id: 10, characters: "व", matras: "ॉ" },
          { lesson_id: 11, characters: "ल 1 2 3 4", matras: "" },
          { lesson_id: 12, characters: "स य 5", matras: ", ." },
          { lesson_id: 13, characters: "6 7 8 9 0", matras: "" },
          { lesson_id: 14, characters: "", matras: "- ृ" },
          { lesson_id: 15, characters: "ओ ए अ इ ऱ ख थ छ", matras: "" },
          { lesson_id: 16, characters: "उ फ", matras: "" },
          { lesson_id: 17, characters: "औ ऐ आ ई ङ घ ध झ", matras: "" },
          { lesson_id: 18, characters: "ऊ भ", matras: "" },
          { lesson_id: 19, characters: "ठ ण", matras: "ँ" },
          { lesson_id: 20, characters: "ळ श ष य़", matras: "।" },
          { lesson_id: 21, characters: "ऍ ढ", matras: "ॅ ्र र्" },
          { lesson_id: 22, characters: "ज्ञ त्र क्ष श्र ञ ऑ", matras: "" },
          { lesson_id: 23, characters: "( ) ऋ", matras: "ः" },
          { lesson_id: 24, characters: "क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह ज्ञ त्र क्ष श्र ञ ऑ", matras: "ा ि ी ु ू ृ े ै ो ौ ं ः" }  
        ];
