const words = [
 { original_word: "Abundant", hindi_translation: "प्रचुर", synonyms: "plentiful ample bountiful" },
  { original_word: "Abolish", hindi_translation: "समाप्त करना", synonyms: "Abrogate" },
  { original_word: "Abash", hindi_translation: "शर्मिंदा करना", synonyms: "Disconcert rattle" },
  { original_word: "Absolve", hindi_translation: "क्षमा करना", synonyms: "Pardon forgive" },
  { original_word: "Acumen", hindi_translation: "प्रखर बुद्धि", synonyms: "Awareness brilliance" },
  { original_word: "Accord", hindi_translation: "समझौता", synonyms: "Agreement harmony" },
  { original_word: "Adamant", hindi_translation: "हठी", synonyms: "Stubborn inflexible" },
  { original_word: "Adversity", hindi_translation: "विपत्ति", synonyms: "Misfortune calamity" },
  { original_word: "Alleviate", hindi_translation: "कम करना", synonyms: "Abate relieve" },
  { original_word: "Amplify", hindi_translation: "बढ़ाना", synonyms: "Augment deepen" },
  { original_word: "Ascend", hindi_translation: "चढ़ना", synonyms: "Escalate" },
  { original_word: "Audacity", hindi_translation: "साहस", synonyms: "Boldness Courage" },
  { original_word: "Awkward", hindi_translation: "बेढंगा", synonyms: "Rude blundering" },
  { original_word: "Axiom", hindi_translation: "स्वयंसिद्ध", synonyms: "Adage truism" },
  { original_word: "Baffle", hindi_translation: "घबरा देना", synonyms: "Astound Faze" },
  { original_word: "Bewitching", hindi_translation: "मोहक", synonyms: "Alluring charming" },
  { original_word: "Bustle", hindi_translation: "हलचल", synonyms: "Commotion Tumult" },
  { original_word: "Busy", hindi_translation: "व्यस्त", synonyms: "Active Engaged" },
  { original_word: "Calamity", hindi_translation: "आपदा", synonyms: "adversity misfortune" },
  { original_word: "Callous", hindi_translation: "संवेदनहीन", synonyms: "obdurate unfeeling" },
  { original_word: "Cease", hindi_translation: "समाप्त करना", synonyms: "terminate desist" },
  { original_word: "Chaste", hindi_translation: "पवित्र", synonyms: "virtuous pure" },
  { original_word: "Comprise", hindi_translation: "शामिल करना", synonyms: "include contain" },
  { original_word: "Classic", hindi_translation: "शास्त्रीय", synonyms: "Simple Typical" },
  { original_word: "Concur", hindi_translation: "सहमत होना", synonyms: "approve agree" },
  { original_word: "Consolidate", hindi_translation: "मजबूत करना", synonyms: "solidify strengthen" },
  { original_word: "Compress", hindi_translation: "संक्षेप करना", synonyms: "Abbreviate Shrink" },
  { original_word: "Decipher", hindi_translation: "व्याख्या करना", synonyms: "interpret reveal" },
  { original_word: "Demolish", hindi_translation: "ढहा देना", synonyms: "Ruin devastate" },
  { original_word: "Dwarf", hindi_translation: "बौना", synonyms: "Diminutive Petite" },
  { original_word: "Eager", hindi_translation: "उत्सुक", synonyms: "Keen acquisitive" },
  { original_word: "Endeavour", hindi_translation: "प्रयास", synonyms: "undertake aspire" },
  { original_word: "Enormous", hindi_translation: "विशाल", synonyms: "colossal mammoth" },
  { original_word: "Epitome", hindi_translation: "प्रतिमान", synonyms: "precise example" },
  { original_word: "Fabricate", hindi_translation: "गढ़ना", synonyms: "construct produce" },
  { original_word: "Feeble", hindi_translation: "कमज़ोर", synonyms: "weak frail" },
  { original_word: "Ferocious", hindi_translation: "भयंकर", synonyms: "cruel fierce" },
  { original_word: "Feud", hindi_translation: "झगड़ा", synonyms: "strife quarrel" },
  { original_word: "Fluctuate", hindi_translation: "हिलना", synonyms: "deflect vacillate" },
  { original_word: "Gather", hindi_translation: "संग्रह करना", synonyms: "Converge huddle" },
  { original_word: "Gorgeous", hindi_translation: "आकर्षक", synonyms: "magnificent dazzling" },
    { original_word: "Gracious", hindi_translation: "दयालु", synonyms: "courteous beneficent" },
  { original_word: "Genuine", hindi_translation: "असली", synonyms: "Absolute Factual" },
  { original_word: "Gloomy", hindi_translation: "उदास", synonyms: "Bleak cloudy" },
  { original_word: "Hamper", hindi_translation: "बाधा डालना", synonyms: "retard prevent" },
  { original_word: "Hazard", hindi_translation: "जोखिम", synonyms: "Peril danger" },
  { original_word: "Humble", hindi_translation: "विनम्र", synonyms: "Meek Timid" },
  { original_word: "Humility", hindi_translation: "विनम्रता", synonyms: "Resignation Fawning" },
  { original_word: "Impulsive", hindi_translation: "आवेगशील", synonyms: "Flaky Impetuous" },
  { original_word: "Interesting", hindi_translation: "रोचक", synonyms: "Enchanting Riveting" },
  { original_word: "Immaculate", hindi_translation: "निर्मल", synonyms: "unsullied spotless" },
  { original_word: "Immerse", hindi_translation: "डुबाना", synonyms: "submerge involve" },
  { original_word: "Imminent", hindi_translation: "आसन्न", synonyms: "impending brewing" },
  { original_word: "Inevitable", hindi_translation: "अनिवार्य", synonyms: "unavoidable ascertained" },
  { original_word: "Infringe", hindi_translation: "उल्लंघन करना", synonyms: "violate encroach" },
  { original_word: "Jaded", hindi_translation: "थका हुआ", synonyms: "tired exhausted" },
  { original_word: "Justify", hindi_translation: "सिद्ध करना", synonyms: "defend exculpate" },
  { original_word: "Juvenile", hindi_translation: "किशोर", synonyms: "young tender" },
  { original_word: "Keen", hindi_translation: "तीव्र", synonyms: "sharp poignant" },
  { original_word: "Lavish", hindi_translation: "बहुतायत", synonyms: "abundant excessive" },
  { original_word: "Lenient", hindi_translation: "दयालु", synonyms: "compassionate merciful" },
  { original_word: "Liable", hindi_translation: "उत्तरदायी", synonyms: "accountable bound" },
  { original_word: "Liberal", hindi_translation: "उदार", synonyms: "magnanimous generous" },
  { original_word: "Linger", hindi_translation: "ठहरना", synonyms: "loiter prolong" },
  { original_word: "Luscious", hindi_translation: "स्वादिष्ट", synonyms: "palatable delicious" },
  { original_word: "Mandatory", hindi_translation: "अनिवार्य", synonyms: "Imperative requisite" },
  { original_word: "Masculine", hindi_translation: "पौरुषपूर्ण", synonyms: "Gallant strapping" },
  { original_word: "Modest", hindi_translation: "विनम्र", synonyms: "humble courteous" },
  { original_word: "Mutual", hindi_translation: "पारस्परिक", synonyms: "joint identical" },
  { original_word: "Nimble", hindi_translation: "चुस्त", synonyms: "prompt brisk" },
  { original_word: "Nonchalant", hindi_translation: "उदासीन", synonyms: "indifferent negligent" },
  { original_word: "Nullify", hindi_translation: "रद्द करना", synonyms: "cancel annul" },
  { original_word: "Numerous", hindi_translation: "अनेकों", synonyms: "profuse various" },
  { original_word: "Obstruct", hindi_translation: "बाधा देना", synonyms: "impede prevent" },
  { original_word: "Obtain", hindi_translation: "प्राप्त करना", synonyms: "Access Inherit" },
  { original_word: "Obvious", hindi_translation: "स्पष्ट", synonyms: "Evident apparent" },
  { original_word: "Optimist", hindi_translation: "आशावादी", synonyms: "Idealist" },
  { original_word: "Pacify", hindi_translation: "शांत करना", synonyms: "Appease Chasten" },
  { original_word: "Persuade", hindi_translation: "मनाना", synonyms: "Cajole Impress" },
  { original_word: "Propagate", hindi_translation: "प्रचार करना", synonyms: "Inseminate fecundate" },
  { original_word: "Progress", hindi_translation: "उन्नति", synonyms: "Pace Betterment" },
  { original_word: "Prompt", hindi_translation: "तत्काल", synonyms: "Precise Punctual" },
  { original_word: "Prudence", hindi_translation: "विवेक", synonyms: "Vigilance Discretion" },
  { original_word: "Pompous", hindi_translation: "घमंडी", synonyms: "haughty arrogant" },
  { original_word: "Quaint", hindi_translation: "अनोखा", synonyms: "Queer strange" },
  { original_word: "Quarantine", hindi_translation: "अलग करना", synonyms: "seclude screen" },
  { original_word: "Rebellious", hindi_translation: "विद्रोही", synonyms: "Restless attacking" },
  { original_word: "Rectify", hindi_translation: "सुधारना", synonyms: "Amend Remedy" },
  { original_word: "Reluctant", hindi_translation: "अनिच्छुक", synonyms: "Cautious Averse" },
  { original_word: "Restrain", hindi_translation: "रोकना", synonyms: "Detain Confine" },
  { original_word: "Redeem", hindi_translation: "मुक्त करना", synonyms: "Recover liberate" },
  { original_word: "Remorse", hindi_translation: "पश्चाताप", synonyms: "Regret penitence" },
  { original_word: "Retract", hindi_translation: "वापस लेना", synonyms: "Recant withdraw" },
  { original_word: "Rustic", hindi_translation: "ग्रामीण", synonyms: "Rural uncivilized" },
  { original_word: "Ruthless", hindi_translation: "निष्ठुर", synonyms: "Remorseless inhumane" },
  { original_word: "Sacred", hindi_translation: "पवित्र", synonyms: "Cherish Divine" },
  { original_word: "Savage", hindi_translation: "जंगली", synonyms: "Wild untamed" },
  { original_word: "Sarcastic", hindi_translation: "व्यंग्यात्मक", synonyms: "Ironical derisive" },
  { original_word: "Sympathy", hindi_translation: "सहानुभूति", synonyms: "Tenderness harmony" },
  { original_word: "System", hindi_translation: "प्रणाली", synonyms: "Scheme Entity" },
  { original_word: "Taboo", hindi_translation: "वर्जित", synonyms: "Prohibit ban" },
  { original_word: "Taciturn", hindi_translation: "मितभाषी", synonyms: "Reserved silent" },
  { original_word: "Tedious", hindi_translation: "थकाऊ", synonyms: "Wearisome Irksome" },
  { original_word: "Temperate", hindi_translation: "संयमी", synonyms: "Cool moderate" },
  { original_word: "Utterly", hindi_translation: "पूर्णतः", synonyms: "Completely entirely" },
  { original_word: "Uncouth", hindi_translation: "असभ्य", synonyms: "Boorish Clownish" },
  { original_word: "Urchin", hindi_translation: "अनाथ बच्चा", synonyms: "Foundling Orphan" },
  { original_word: "Urge", hindi_translation: "प्रेरित करना", synonyms: "Incite Implore" },
  { original_word: "Vanity", hindi_translation: "अहंकार", synonyms: "Conceit pretension" },
  { original_word: "Venom", hindi_translation: "विष", synonyms: "Poison malevolence" },
  { original_word: "Veteran", hindi_translation: "अनुभवी", synonyms: "Ingenious experienced" },
  { original_word: "Vicious", hindi_translation: "दुष्ट", synonyms: "Corrupt obnoxious" },
  { original_word: "Vigilant", hindi_translation: "सावधान", synonyms: "Cautious alert" },
  { original_word: "Wicked", hindi_translation: "दुष्ट", synonyms: "vicious immoral" },
  { original_word: "Wield", hindi_translation: "प्रयोग करना", synonyms: "Exert employ" },
  { original_word: "Winsome", hindi_translation: "आकर्षक", synonyms: "Beautiful Comely" },
  { original_word: "Yell", hindi_translation: "चिल्लाना", synonyms: "shout shriek" },
  { original_word: "Yield", hindi_translation: "समर्पण करना", synonyms: "surrender abdicate" },
  { original_word: "Yearn", hindi_translation: "लालसा करना", synonyms: "languish crave" },
  { original_word: "Zeal", hindi_translation: "उत्साह", synonyms: "eagerness fervor" },
  { original_word: "Zenith", hindi_translation: "चरम", synonyms: "summit apex" },
  { original_word: "Zest", hindi_translation: "उल्लास", synonyms: "delight enthusiasm" },
  { original_word: "Zig-zag", hindi_translation: "टेढ़ा-मेढ़ा", synonyms: "oblique wayward" }
];
